version: "3.9"

services:
  telegram-bot:
    build: .
    container_name: media-check-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - media_data:/app/data

volumes:
  media_data: